config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts do
    collection do
      get :graphs
    end
  end

  match '/posts/catgories/:cat' => 'posts#category_search', via: :get, as: :cat

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :polls

  resources :comments
  resources :votes, only: [:create]

  root 'home#index'

  get '/user_mention' => 'home#user_mention', as: :mentionables


  namespace :api do
  namespace :v1 do
    get 'system/status'

    resources :posts, only: [:index]

    resources :auth, only: [] do
      collection do
        post :orbita
      end
    end
  end
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base
    has_paper_trail
    has_many :vote_options, dependent: :destroy
    validates :topic, presence: true
    accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true

    def normalized_votes_for(option)
      votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
    end

    def votes_summary
      vote_options.inject(0) {|summary, option| summary + option.votes.count}
    end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  before_action :authenticate_user!

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      (User.all.uniq - [current_user]).each do |user|
        Notification.create(recipient: user, actor: current_user, action: "polled", notifiable: @poll)
      end
      flash[:success] = 'Poll was created!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end

  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = 'Poll was destroyed!'
    else
      flash[:warning] = 'Error destroying poll...'
    end
    redirect_to polls_path
  end

  private

  def poll_params
    params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_votes_for(option)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <%= render 'shared/errors', object: @poll %>

  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">Options</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add option', f, :vote_options %>
      </div>
    </div>
  </div>

  <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/polls/_vote_option.html.erb
<div class="form-group">
  <%= content_tag(:label) do %>
    <% unless current_user.voted_for?(@poll) %>
      <%= radio_button_tag 'vote_option[id]', option.id %>
    <% end %>
    <%= option.title %>
  <% end %>
  <%= visualize_votes_for option %>
</div>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>
  <%= link_to_remove_association "remove option", f %>
</div>

app/views/polls/_voting_form.html.erb
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
  <%= hidden_field_tag 'poll[id]', @poll.id %>

  <%= render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option %>

  <p><b>Total votes: <%= @poll.votes_summary %></b></p>

  <% if current_user.voted_for?(@poll) %>
    <p>You have already voted!</p>
  <% else %>
    <%= submit_tag 'Vote', class: 'btn btn-lg btn-primary' %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<% content_for(:page_header) {"Edit poll"} %>

<%= render 'form' %>

app/views/polls/index.html.erb
<% content_for(:page_header) {"Participate in our polls right now!"} %>

<% @polls.each do |poll| %>
  <div class="well">
    <h2><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h2>

    <%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
      <%= hidden_field_tag 'poll[id]', poll.id %>
      <% poll.vote_options.each do |option| %>
        <div class="form-group">
          <%= content_tag(:label) do %>
            <% unless current_user.voted_for?(@poll) %>
              <%= radio_button_tag 'vote_option[id]', option.id %>
            <% end %>
            <%= option.title %>
          <% end %>
          <%= visualize_votes_for option %>
        </div>
      <%end%>
      <p><b>Total votes: <%= poll.votes_summary %></b></p>
      <% if current_user.voted_for?(poll) %>
        <p>You have already voted!</p>
      <% else %>
        <%= submit_tag 'Vote', class: 'btn btn-lg btn-primary' %>
      <% end %>
    <% end %>
    <br/>
    <div class="btn-group">
      <%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
      <%= link_to 'Delete', poll_path(poll), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
    </div>
  </div>
<% end %>


<style>
    .well {
        h2 {
            margin-top: 0;
        }
    }
</style>

app/views/polls/new.html.erb
<% content_for(:page_header) {"Create a new poll"} %>

<%= render 'form' %>

app/views/polls/show.html.erb
<% content_for(:page_header) {"Share your opinion"} %>

<h2><%= @poll.topic %></h2>

<%= render 'voting_form' %>