config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts do
    collection do
      get :graphs
    end
  end

  match '/posts/catgories/:cat' => 'posts#category_search', via: :get, as: :cat

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :polls

  resources :comments
  resources :votes, only: [:create]

  root 'home#index'

  get '/user_mention' => 'home#user_mention', as: :mentionables


  namespace :api do
  namespace :v1 do
    get 'system/status'

    resources :posts, only: [:index]

    resources :auth, only: [] do
      collection do
        post :orbita
      end
    end
  end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_paper_trail
  acts_as_commentable
  belongs_to :user
  # has_many :comments
  has_many :category_posts, dependent: :destroy
  has_many :categories, :through => :category_posts

  def mentions
    @mentions ||= begin
      regex = /@([\w]+)/
      description.scan(regex).flatten
    end
  end

  def mentioned_users
    @mentioned_users ||= User.where(name: mentions)
  end


end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController


  api :GET, '/posts', "Gets the filtered list of posts"
  def index

    posts = Post.where(user_id: api_current_user.id).all

    serialize_resources posts, ::V1::PostListSerializer
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at DESC').all
    @categories = Category.all
    respond_to do |format|
      format.html
      format.xlsx
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @user_who_commented = current_user
    @comment = Comment.build_from( @post, @user_who_commented.id, "" )
    @categories = Category.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @categories = Category.all
    # @post_user = User.all
    respond_to do |format|
      CategoryPost.create(:project_id => @post.id)
      if @post.save
        (User.all.uniq - [current_user]).each do |user|
          Notification.create(recipient: user, actor: current_user, action: "posted", notifiable: @post)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @categories = Category.all

    respond_to do |format|
      @post.user_id = current_user.id
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def category_search
    @selected_id = params[:cat]
    @post_sel = CategoryPost.where(:category_id => @selected_id)
  end

  def graphs
    @edges = CategoryPost.all
    @nodes = Post.all
    @cats = Category.all
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    # def linked_users(body)
    #   body.gsub /@([\w]+)/ do |match|
    #     link_to match, user_path($1)
    #   end.html_safe
    # end

end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="card-body">
    <form>
      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, style: 'width:100%'%>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description , style: 'width:100%', rows: 10, data: {behavior: "autocomplete"}%>

        <script>

        $(function(){
            data = '/user_mention.json';
            $('[data-behavior="autocomplete"]').atwho(
              {
                at:"@",
                'data':data
              }
            );
        });
        </script>

      </div>
      <div class="form-group" style="width:100%;">
        <%= f.input :category_ids, collection: Category.all,  as: :check_boxes  %>
      </div>
    </form>

    <div class="form-group" style="display:none;">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

  </div>


<% end %>

app/views/posts/category_search.html.erb
<%=debug(@selected_id)%>

<%=debug(@post_sel)%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/graphs.html.erb
<!-- START SIGMA IMPORTS -->
<script src="/layout/js/sigma/src/sigma.core.js"></script>
<script src="/layout/js/sigma/src/conrad.js"></script>
<script src="/layout/js/sigma/src/utils/sigma.utils.js"></script>
<script src="/layout/js/sigma/src/utils/sigma.polyfills.js"></script>
<script src="/layout/js/sigma/src/sigma.settings.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.dispatcher.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.configurable.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.graph.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.camera.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.quad.js"></script>
<script src="/layout/js/sigma/src/classes/sigma.classes.edgequad.js"></script>
<script src="/layout/js/sigma/src/captors/sigma.captors.mouse.js"></script>
<script src="/layout/js/sigma/src/captors/sigma.captors.touch.js"></script>
<script src="/layout/js/sigma/src/renderers/sigma.renderers.canvas.js"></script>
<script src="/layout/js/sigma/src/renderers/sigma.renderers.webgl.js"></script>
<script src="/layout/js/sigma/src/renderers/sigma.renderers.svg.js"></script>
<script src="/layout/js/sigma/src/renderers/sigma.renderers.def.js"></script>
<script src="/layout/js/sigma/src/renderers/webgl/sigma.webgl.nodes.def.js"></script>
<script src="/layout/js/sigma/src/renderers/webgl/sigma.webgl.nodes.fast.js"></script>
<script src="/layout/js/sigma/src/renderers/webgl/sigma.webgl.edges.def.js"></script>
<script src="/layout/js/sigma/src/renderers/webgl/sigma.webgl.edges.fast.js"></script>
<script src="/layout/js/sigma/src/renderers/webgl/sigma.webgl.edges.arrow.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.labels.def.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.hovers.def.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.nodes.def.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edges.def.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edges.curve.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edges.arrow.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edges.curvedArrow.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edgehovers.def.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edgehovers.curve.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edgehovers.arrow.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.edgehovers.curvedArrow.js"></script>
<script src="/layout/js/sigma/src/renderers/canvas/sigma.canvas.extremities.def.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.utils.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.nodes.def.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.edges.def.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.edges.curve.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.labels.def.js"></script>
<script src="/layout/js/sigma/src/renderers/svg/sigma.svg.hovers.def.js"></script>
<script src="/layout/js/sigma/src/middlewares/sigma.middlewares.rescale.js"></script>
<script src="/layout/js/sigma/src/middlewares/sigma.middlewares.copy.js"></script>
<script src="/layout/js/sigma/src/misc/sigma.misc.animation.js"></script>
<script src="/layout/js/sigma/src/misc/sigma.misc.bindEvents.js"></script>
<script src="/layout/js/sigma/src/misc/sigma.misc.bindDOMEvents.js"></script>
<script src="/layout/js/sigma/src/misc/sigma.misc.drawHovers.js"></script>
<!-- END SIGMA IMPORTS -->

<div class="container">
  <style>
    #graph-container {
      top: 70px;
      bottom: 0;
      left: 0;
      right: 0;
      position: absolute;
    }
  </style>
  <div class="row">
     <div id="graph-container"></div>
  </div>
</div>
<script>
/**
 * This is a basic example on how to instantiate sigma. A random graph is
 * generated and stored in the "graph" variable, and then sigma is instantiated
 * directly with the graph.
 *
 * The simple instance of sigma is enough to make it render the graph on the on
 * the screen, since the graph is given directly to the constructor.
 */



var i,
    s,
    posts= [],
    cats = [],
    g = {
      nodes: [],
      edges: []
    };


  <%@cats.each do |c|%>
    cats.push({
      id: 'c'+ <%=c.id%>,
      label: '<%=c.name%>',
      x: Math.random(),
      y: Math.random(),
      size: Math.random(),
      color: '#666'
    });
  <%end%>

  <%@nodes.each do |n|%>
    posts.push({
      id: 'n'+ <%=n.id%>,
      label: '<%=n.title%>',
      x: Math.random(),
      y: Math.random(),
      size: Math.random(),
      color: '#666'
    });
  <%end%>

  g.nodes = posts.concat(cats);

// Generate a random graph:
// for (i = 0; i < N; i++)


// g.nodes.push({

// });


// for (i = 0; i < E; i++)
<%@edges.each do |e|%>
  g.edges.push({
    id: 'e' + <%=e.id%>,
    source: 'n' + <%=e.post_id%>,
    target: 'c' + <%=e.category_id%>,
    size: Math.random(),
    color: '#ccc'
  });
<%end%>

  var N = g.nodes.length,
      E = <%= @edges.count%>;


// Instantiate sigma:
s = new sigma({
  graph: g,
  container: 'graph-container'
});
</script>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8">
      <!-- Blog Post -->
      <% @posts.each do |post| %>
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><%= post.title %></h2>
          <p class="card-text"><%= post.description %></p>
          <%= link_to 'Read More', post, class: 'btn btn-success' %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', post, class: 'btn btn-danger' ,method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="card-footer text-muted">
          Posted on January 1, 2017 by
          <a href="#"><%= post.user.name %></a>
        </div>
      </div>
      <%end%>


    </div>




    <div class="col-md-4">
      <!-- Categories Widget -->
      <div class="card my-4">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <%= link_to 'New Post', new_post_path %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card my-4">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-12">
              <h3>Categories</h3>
              <ul class="list-unstyled mb-0">
              <%@categories.each do |cat|%>
                <li>
                <%=link_to cat.name, cat_path(cat: cat.id)%>
                </li>
              <%end%>





              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-8">
      <!-- Title -->
      <h1 class="mt-4"><%= @post.title %></h1>
      <!-- Author -->
      <p class="lead"> by <a href="#"><%= @post.user.name %></a></p>
      <hr>
      <!-- Date/Time -->
      <p>Posted on <%= @post.created_at %></p>
      <hr>
      <p><%@post.categories.each do |categ| %>
          <i><%=categ.name%></i>&nbsp;
      <%end%>

      </p>
      <hr>
      <!-- Post Content -->
      <p class="lead"><%= @post.description %> </p>
      <hr>
      <p>
        <strong>Mentions:</strong>
        <% @post.mentioned_users.each do |m|%>
        <%=m.name%>
        <%end%>
      </p>

      <hr>
      <!-- Comments Form -->
      <%= render partial: "comments/form"%>

      <%= render partial: "comments/reply", locals: {comments: @comment.commentable.root_comments} %>

    </div>


    <div class="col-md-4">
      <!-- Categories Widget -->
      <div class="card my-4">
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %>
                  &nbsp;<%= link_to 'Back', posts_path, class: 'btn btn-default'%>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>