config/routes.rb
Rails.application.routes.draw do

  apipie
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts do
    collection do
      get :graphs
    end
  end

  match '/posts/catgories/:cat' => 'posts#category_search', via: :get, as: :cat

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :polls

  resources :comments
  resources :votes, only: [:create]

  root 'home#index'

  get '/user_mention' => 'home#user_mention', as: :mentionables


  namespace :api do
  namespace :v1 do
    get 'system/status'

    resources :posts, only: [:index]

    resources :auth, only: [] do
      collection do
        post :orbita
      end
    end
  end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :category_posts
    has_many :posts, :through => :category_posts
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
    belongs_to :recipient, class_name: "User"
    belongs_to :actor, class_name: "User"
    belongs_to :notifiable, polymorphic: true

    scope :unread, ->{ where(read_at: nil) }
    scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/poll.rb
class Poll < ActiveRecord::Base
    has_paper_trail
    has_many :vote_options, dependent: :destroy
    validates :topic, presence: true
    accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true

    def normalized_votes_for(option)
      votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
    end

    def votes_summary
      vote_options.inject(0) {|summary, option| summary + option.votes.count}
    end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_paper_trail
  acts_as_commentable
  belongs_to :user
  # has_many :comments
  has_many :category_posts, dependent: :destroy
  has_many :categories, :through => :category_posts

  def mentions
    @mentions ||= begin
      regex = /@([\w]+)/
      description.scan(regex).flatten
    end
  end

  def mentioned_users
    @mentioned_users ||= User.where(name: mentions)
  end


end

app/models/post_creator.rb
class PostCreator < ActiveRecord::Base
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

    has_many :votes, dependent: :destroy
    has_many :vote_options, through: :votes
    has_many :posts
    has_many :comments

    has_paper_trail

    include Oauth51Client::User

     def self.from_omniauth(auth)
       random_psw = Devise.friendly_token[0,20]

       this_user = where(o51_uid: auth.uid).first_or_initialize do |user|
         user.email = auth.info.email
         user.password = random_psw
         user.password_confirmation = random_psw
       end

       # Let's apply fresh data
       this_user.o51_authentication_token = auth.credentials.token
       this_user.o51_authentication_token_secret = auth.credentials.refresh_token
       this_user.o51_expires_at = (Time.at(auth.credentials.expires_at) rescue nil)

       # o51_client is defined in oauth51-client gem
       profile = this_user.o51_client.me
       this_user.o51_points = profile['points']
       this_user.o51_picture_url = profile['avatar_url']
       this_user.o51_authentication_token = auth.credentials.token
       this_user.o51_authentication_token_secret= auth.credentials.refresh_token
       this_user.o51_profile = profile.to_json
       this_user.save
       this_user
     end

    def voted_for?(poll)
      vote_options.any? {|v| v.poll == poll }
    end

    # def voted_for?(poll)
    #   votes.any? {|v| v.vote_option.poll == poll}
    # end

    # def voted_for?(poll)
    #   vote_options(true).any? {|v| v.poll == poll }
    # end

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    has_paper_trail
    belongs_to :user
    belongs_to :vote_option
end

app/models/vote_option.rb
class VoteOption < ActiveRecord::Base
    has_paper_trail
  belongs_to :poll
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
        redirect_to polls_path
    else
        redirect_to new_user_session_path
    end
  end

  def user_mention
    render json: User.all, root: false
  end



end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  before_action :authenticate_user!

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      (User.all.uniq - [current_user]).each do |user|
        Notification.create(recipient: user, actor: current_user, action: "polled", notifiable: @poll)
      end
      flash[:success] = 'Poll was created!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated!'
      redirect_to polls_path
    else
      render 'edit'
    end
  end

  def destroy
    @poll = Poll.find_by_id(params[:id])
    if @poll.destroy
      flash[:success] = 'Poll was destroyed!'
    else
      flash[:warning] = 'Error destroying poll...'
    end
    redirect_to polls_path
  end

  private

  def poll_params
    params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_votes_for(option)
    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar',
                  style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    # def linked_users(body)
    #   body.gsub /@([\w]+)/ do |match|
    #     link_to match, user_path($1)
    #   end.html_safe
    # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poller</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" media="screen" href="/layout/css/custom.css">
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Poller', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
              <%= link_to 'Add poll', new_poll_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Posts', posts_path , class: "nav-link" %>
      </li>
      <%if user_signed_in?%>

      <li class="nav-item btn-group dropdown" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
           <a class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <i class="em em-bell"></i> <span id="notification-number" data-behavior="unread-count" ></span>
           </a>
           <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items" id="notification-items">
             <!--
             <a class="dropdown-item" href="#">Action</a>
             <a class="dropdown-item" href="#">Another action</a>
             <a class="dropdown-item" href="#">Something else here</a>
             -->
           </ul>
       </li>


        <li><p>Hello, <%=current_user.name%> - <%= link_to "Sign out", destroy_user_session_path, class: "btn btn-danger navbar-btn", :method => 'delete' %></p></li>
      <%else%>
        <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-success navbar-btn" %></li>
      <%end%>

    </ul>
  </div>
</nav>


<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <div class="page-header">
    <h1><%= yield :page_header %></h1>
  </div>

  <%= yield %>
</div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4>The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>